- group: { name: dollar, enabled: true }
- group: { name: generalise, enabled: true }
- ignore: { name: Use lambda-case }
- ignore: { name: Use list comprehension }
- ignore: { name: Use newtype instead of data }
- ignore: { name: Use tuple-section }
